displayName: TLS headers
type: middleware
iconPath: .assets/icon.png

import: github.com/RiskIdent/traefik-tls-headers-plugin
basePkg: plugin

summary: 'Add TLS information to request headers'

testData:
  headers:
    cipher: X-Tls-Cipher
